(function registerData(CQ) {
  CQ.STORAGE_KEY = "clavierQuestScores:v1";
  CQ.LANGUAGE_STORAGE_KEY = "clavierQuestLanguage:v1";
  CQ.DEFAULT_LANGUAGE = "fr";

  CQ.languages = [
    { id: "fr", label: "FR", name: "Français" },
    { id: "en", label: "EN", name: "English" },
    { id: "es", label: "ES", name: "Español" },
  ];

  CQ.difficultySettings = {
    calme: {
      speed: 0.82,
      spawn: 1.15,
      time: 75,
      lives: 6,
      tokens: 6,
    },
    rythme: {
      speed: 1,
      spawn: 0.9,
      time: 65,
      lives: 5,
      tokens: 8,
    },
    defi: {
      speed: 1.22,
      spawn: 0.7,
      time: 55,
      lives: 4,
      tokens: 10,
    },
  };

  CQ.gradeTuning = {
    "5e": {
      speedMultiplier: 1,
      spawnMultiplier: 1,
      timeMultiplier: 1,
      livesDelta: 0,
      tokensDelta: 0,
      wordTargetBonus: 0,
      shortcutGoalBonus: 0,
      meteorExtraPool: 0,
    },
    "4e": {
      speedMultiplier: 1.18,
      spawnMultiplier: 0.82,
      timeMultiplier: 0.9,
      livesDelta: -1,
      tokensDelta: 2,
      wordTargetBonus: 2,
      shortcutGoalBonus: 3,
      meteorExtraPool: 4,
    },
  };

  CQ.gameCards = [
    {
      id: "meteors",
      art: ["A", "Z", "E", "R", "T", "Y", "U", "I", "O", "P", "Q", "S"],
    },
    {
      id: "words",
      art: ["é", "q", "u", "a", "t", "i", "o", "n", ".", ";", "?", "!"],
    },
    {
      id: "shortcuts",
      art: ["Ctrl", "C", "V", "Z", "S", "F", "Tab", "↵", "Esc", "B", "I", "U"],
    },
    {
      id: "maze",
      art: ["↑", "←", "↓", "→", "Z", "Q", "S", "D", "A", "E", "R", "T"],
    },
    {
      id: "symbols",
      art: ["@", "#", "€", "_", "{", "}", "[", "]", "|", "\\", "~", "^"],
    },
    {
      id: "cipher",
      art: ["@", "€", "#", "?", "!", "{", "}", "~", "|", "[", "]", "\\"],
    },
    {
      id: "formula",
      art: ["@", "#", "€", "=", "+", ":", "/", "_", ".", "-", "{", "}"],
    },
    {
      id: "rpg",
      art: ["@", "#", "€", "{", "}", "PNJ", "↵", "Z", "Q", "S", "D", "✓"],
    },
  ];

  CQ.symbolSets = {
    "5e": [
      { symbol: "@", combo: "AltGr + 0", modifier: "AltGr" },
      { symbol: "#", combo: "AltGr + 3", modifier: "AltGr" },
      { symbol: "€", combo: "AltGr + E", modifier: "AltGr" },
      { symbol: "_", combo: "8", modifier: "direct" },
      { symbol: "-", combo: "6", modifier: "direct" },
      { symbol: "?", combo: "Maj + ,", modifier: "Maj" },
      { symbol: "!", combo: "Maj + 8", modifier: "Maj" },
      { symbol: ".", combo: "Maj + ;", modifier: "Maj" },
      { symbol: "/", combo: "Maj + :", modifier: "Maj" },
      { symbol: ":", combo: ".", modifier: "direct" },
    ],
    "4e": [
      { symbol: "@", combo: "AltGr + 0", modifier: "AltGr" },
      { symbol: "#", combo: "AltGr + 3", modifier: "AltGr" },
      { symbol: "€", combo: "AltGr + E", modifier: "AltGr" },
      { symbol: "{", combo: "AltGr + 4", modifier: "AltGr" },
      { symbol: "}", combo: "AltGr + =", modifier: "AltGr" },
      { symbol: "[", combo: "AltGr + 5", modifier: "AltGr" },
      { symbol: "]", combo: "AltGr + )", modifier: "AltGr" },
      { symbol: "|", combo: "AltGr + 6", modifier: "AltGr" },
      { symbol: "\\", combo: "AltGr + 8", modifier: "AltGr" },
      { symbol: "~", combo: "AltGr + 2", modifier: "AltGr" },
      { symbol: "_", combo: "8", modifier: "direct" },
      { symbol: "^", combo: "touche ^", modifier: "direct" },
      { symbol: "?", combo: "Maj + ,", modifier: "Maj" },
      { symbol: "!", combo: "Maj + 8", modifier: "Maj" },
      { symbol: "/", combo: "Maj + :", modifier: "Maj" },
    ],
  };

  CQ.rpgQuests = {
    fr: [
      { id: "mail", x: 8, y: 5, icon: "@", npc: "Messager Pixel", title: "Le portail @", prompt: "Le portail du collège réclame le symbole arobase.", answer: "@", type: "text" },
      { id: "tag", x: 15, y: 7, icon: "#", npc: "Archiviste Hashtag", title: "Le mur des hashtags", prompt: "Inscris le symbole qui lance un mot-clé.", answer: "#", type: "text" },
      { id: "euro", x: 27, y: 7, icon: "€", npc: "Marchande d'euros", title: "La boutique en euros", prompt: "La caisse magique attend le signe de la monnaie européenne.", answer: "€", type: "text" },
      { id: "braces", x: 32, y: 10, icon: "{}", npc: "Forgeron AltGr", title: "La forge des accolades", prompt: "Reproduis le couple d'accolades.", answer: "{}", type: "text" },
      { id: "brackets", x: 12, y: 14, icon: "[]", npc: "Gardienne des tableaux", title: "La salle des crochets", prompt: "Ouvre et ferme un tableau avec les crochets.", answer: "[]", type: "text" },
      { id: "bar", x: 22, y: 14, icon: "|", npc: "Oracle logique", title: "Le pont logique", prompt: "Tape la barre verticale qui sépare deux choix.", answer: "|", type: "text" },
      { id: "slash", x: 35, y: 16, icon: "\\", npc: "Exploratrice système", title: "Le chemin inverse", prompt: "Tape la barre oblique inverse.", answer: "\\", type: "text" },
      { id: "accents", x: 7, y: 19, icon: "é", npc: "Scribe des accents", title: "Le manuscrit accentué", prompt: "Écris ces accents dans l'ordre.", answer: "éèàç", type: "text" },
      { id: "shortcut", x: 18, y: 21, icon: "Ctrl", npc: "Maître Annulation", title: "Le raccourci oublié", prompt: "Lance le raccourci pour annuler.", answer: "Ctrl+Z", type: "combo" },
      { id: "final", x: 31, y: 22, icon: "★", npc: "Gardienne finale", title: "Le grand examen clavier", prompt: "Mélange final : arobase, hashtag, euro, point d'interrogation.", answer: "@#€?", type: "text" },
    ],
    en: [
      { id: "mail", x: 8, y: 5, icon: "@", npc: "Pixel Messenger", title: "The @ Gate", prompt: "The school portal asks for the at sign.", answer: "@", type: "text" },
      { id: "tag", x: 15, y: 7, icon: "#", npc: "Hashtag Archivist", title: "The Hashtag Wall", prompt: "Type the symbol that starts a keyword.", answer: "#", type: "text" },
      { id: "euro", x: 27, y: 7, icon: "€", npc: "Euro Merchant", title: "The Euro Shop", prompt: "The magic register expects the European currency sign.", answer: "€", type: "text" },
      { id: "braces", x: 32, y: 10, icon: "{}", npc: "AltGr Smith", title: "The Brace Forge", prompt: "Reproduce the pair of braces.", answer: "{}", type: "text" },
      { id: "brackets", x: 12, y: 14, icon: "[]", npc: "Array Guardian", title: "The Bracket Hall", prompt: "Open and close an array with brackets.", answer: "[]", type: "text" },
      { id: "bar", x: 22, y: 14, icon: "|", npc: "Logic Oracle", title: "The Logic Bridge", prompt: "Type the vertical bar that separates two choices.", answer: "|", type: "text" },
      { id: "slash", x: 35, y: 16, icon: "\\", npc: "System Explorer", title: "The Reverse Path", prompt: "Type the backslash.", answer: "\\", type: "text" },
      { id: "accents", x: 7, y: 19, icon: "é", npc: "Accent Scribe", title: "The Accent Manuscript", prompt: "Type these accents in order.", answer: "éèàç", type: "text" },
      { id: "shortcut", x: 18, y: 21, icon: "Ctrl", npc: "Undo Master", title: "The Forgotten Shortcut", prompt: "Trigger the shortcut for undo.", answer: "Ctrl+Z", type: "combo" },
      { id: "final", x: 31, y: 22, icon: "★", npc: "Final Guardian", title: "The Grand Keyboard Trial", prompt: "Final mix: at sign, hashtag, euro, question mark.", answer: "@#€?", type: "text" },
    ],
    es: [
      { id: "mail", x: 8, y: 5, icon: "@", npc: "Mensajero Pixel", title: "El portal @", prompt: "El portal del colegio pide la arroba.", answer: "@", type: "text" },
      { id: "tag", x: 15, y: 7, icon: "#", npc: "Archivista Hashtag", title: "El muro de hashtags", prompt: "Escribe el símbolo que inicia una palabra clave.", answer: "#", type: "text" },
      { id: "euro", x: 27, y: 7, icon: "€", npc: "Mercader de euros", title: "La tienda en euros", prompt: "La caja mágica espera el signo de moneda europea.", answer: "€", type: "text" },
      { id: "braces", x: 32, y: 10, icon: "{}", npc: "Herrero AltGr", title: "La forja de llaves", prompt: "Reproduce la pareja de llaves.", answer: "{}", type: "text" },
      { id: "brackets", x: 12, y: 14, icon: "[]", npc: "Guardiana de tablas", title: "La sala de corchetes", prompt: "Abre y cierra una tabla con corchetes.", answer: "[]", type: "text" },
      { id: "bar", x: 22, y: 14, icon: "|", npc: "Oráculo lógico", title: "El puente lógico", prompt: "Escribe la barra vertical que separa dos opciones.", answer: "|", type: "text" },
      { id: "slash", x: 35, y: 16, icon: "\\", npc: "Exploradora del sistema", title: "El camino inverso", prompt: "Escribe la barra inversa.", answer: "\\", type: "text" },
      { id: "accents", x: 7, y: 19, icon: "é", npc: "Escriba de acentos", title: "El manuscrito acentuado", prompt: "Escribe estos acentos en orden.", answer: "éèàç", type: "text" },
      { id: "shortcut", x: 18, y: 21, icon: "Ctrl", npc: "Maestro Deshacer", title: "El atajo olvidado", prompt: "Activa el atajo para deshacer.", answer: "Ctrl+Z", type: "combo" },
      { id: "final", x: 31, y: 22, icon: "★", npc: "Guardiana final", title: "El gran examen de teclado", prompt: "Mezcla final: arroba, hashtag, euro, signo de interrogación.", answer: "@#€?", type: "text" },
    ],
  };

  CQ.translations = {
    fr: {
      meta: {
        title: "Clavier Quest - 5e / 4e",
      },
      aria: {
        home: "Retour accueil",
        language: "Langue",
        sound: "Son",
        settings: "Réglages de session",
        grade: "Niveau scolaire",
        intensity: "Intensité",
      },
      home: {
        eyebrow: "Entraînement clavier",
        title: "Des mini-jeux courts pour gagner en précision.",
        description: "Sélectionne un niveau, choisis un défi, puis joue au clavier. Les scores restent enregistrés dans ce navigateur.",
        choose: "Choisis ton entraînement",
      },
      controls: {
        grade: "Niveau",
        intensity: "Intensité",
      },
      actions: {
        home: "← Accueil",
        homeShort: "Accueil",
        replay: "Rejouer",
        reset: "Remettre les scores à zéro",
      },
      hud: {
        score: "Score",
        combo: "Série",
        accuracy: "Précision",
      },
      score: {
        best: "Meilleur score : {score}",
        record: "Record {score}",
        new: "Nouveau",
      },
      difficulties: {
        calme: "Calme",
        rythme: "Rythme",
        defi: "Défi",
      },
      results: {
        eyebrow: "Session terminée",
        success: "Mission réussie",
        finished: "Session terminée",
        summary: "{title} : {score} points, {accuracy} de précision. {message}",
      },
      play: {
        defaultMode: "Mini-jeu",
        defaultTitle: "Jeu",
      },
      games: {
        meteors: {
          title: "Météores de touches",
          mode: "Réflexes",
          summary: "Des touches tombent : vise juste, garde la série et protège la ligne.",
          tag: "lettres",
        },
        words: {
          title: "Atelier des mots",
          mode: "Précision",
          summary: "Écris des mots et phrases de cours sans perdre le fil.",
          tag: "mots",
        },
        shortcuts: {
          title: "Raccourcis express",
          mode: "Méthode",
          summary: "Enchaîne les raccourcis utiles pour travailler plus vite.",
          tag: "Ctrl",
        },
        maze: {
          title: "Labyrinthe clavier",
          mode: "Déplacement",
          summary: "Explore, ouvre les bornes et rejoins la sortie avant la fin.",
          tag: "flèches",
        },
        symbols: {
          title: "Forgeron AltGr",
          mode: "Symboles",
          summary: "Forge @, #, €, accolades et autres touches difficiles avec les bons modificateurs.",
          tag: "AltGr",
        },
        cipher: {
          title: "Code secret",
          mode: "Mémoire",
          summary: "Observe une suite de symboles, puis reproduis-la sans te tromper.",
          tag: "mémo",
        },
        formula: {
          title: "Réparateur de formules",
          mode: "Contexte",
          summary: "Répare des adresses, hashtags et formules en tapant le symbole manquant.",
          tag: "@ # €",
        },
        rpg: {
          title: "Aventure clavier",
          mode: "RPG",
          summary: "Explore une cité top-down, parle aux PNJ et termine 10 quêtes de clavier.",
          tag: "quête",
        },
      },
      meters: {
        time: "Temps",
        progress: "Progression",
        beacons: "Bornes",
        charges: "Charges",
        sequences: "Suites",
        repairs: "Réparations",
        quests: "Quêtes",
      },
      meteor: {
        line: "ligne de concentration",
        lives: "Vies",
        livesCount: "{count} vies",
        lost: "La ligne a été touchée trop souvent.",
        success: "La pluie de touches est maîtrisée.",
        mission: "Appuie sur la touche affichée avant qu'elle traverse la ligne.",
      },
      word: {
        item: "Mot {current} / {target}",
        timeUp: "Le temps est écoulé.",
        success: "La série de mots est validée.",
        enterHint: "Entrée valide aussi une phrase complète",
        mission: "Respecte les accents, les espaces et la ponctuation.",
      },
      shortcut: {
        timeUp: "La manche est terminée.",
        success: "Les raccourcis s'enchaînent avec assurance.",
        correct: "Correct",
        received: "Reçu : {combo}",
        yourTurn: "À toi",
      },
      maze: {
        exitLabel: "S",
        timeUp: "La porte s'est refermée.",
        exitSuccess: "Sortie atteinte.",
        missingBeacons: "Il reste des bornes à activer.",
        beacon: "Borne {label}",
        activate: "Active la touche puis file vers la sortie. Temps : {seconds} s",
        remaining: "{count} bornes restantes",
        move: "Déplacement avec flèches ou ZQSD. Temps : {seconds} s",
      },
      symbols: {
        target: "Symbole cible",
        combo: "Combinaison",
        queue: "file de forge",
        timeUp: "Le temps de forge est écoulé.",
        success: "Les symboles difficiles sont bien forgés.",
        mission: "Tape le symbole affiché. Aide-toi de la combinaison indiquée : AltGr, Maj ou touche directe.",
      },
      cipher: {
        preview: "Observe",
        input: "Reproduis",
        sequence: "Suite {current} / {target}",
        timeUp: "Le coffre s'est verrouillé.",
        success: "Le code secret est mémorisé.",
        wrong: "Suite brouillée, recommence celle-ci.",
        missionPreview: "Mémorise les symboles dans l'ordre.",
        missionInput: "Reproduis la suite sans regarder le modèle.",
      },
      formula: {
        placeholder: "symbole manquant",
        timeUp: "L'atelier de correction ferme.",
        success: "Les lignes sont réparées.",
        mission: "Tape le symbole qui remplace le carré.",
      },
      rpg: {
        timeUp: "La cloche sonne avant la fin de l'aventure.",
        success: "Toutes les quêtes clavier sont validées.",
        moveHint: "Déplace-toi avec les flèches ou ZQSD.",
        interactHint: "Entrée près d'un PNJ pour lancer une quête.",
        completed: "Quête terminée",
        alreadyDone: "Cette quête est déjà validée.",
        answer: "Réponse",
        comboAnswer: "Raccourci attendu",
        enterValidate: "Entrée pour valider. Échap pour fermer.",
        questDone: "{count}/10 quêtes terminées",
        nearby: "Parle à {name}",
        noQuest: "Explore la cité et cherche les symboles.",
      },
    },
    en: {
      meta: {
        title: "Keyboard Quest - Grade 7 / 8",
      },
      aria: {
        home: "Back home",
        language: "Language",
        sound: "Sound",
        settings: "Session settings",
        grade: "School level",
        intensity: "Intensity",
      },
      home: {
        eyebrow: "Keyboard training",
        title: "Short mini-games to build speed and accuracy.",
        description: "Choose a level, pick a challenge, then play with the keyboard. Scores are saved in this browser.",
        choose: "Choose your training",
      },
      controls: {
        grade: "Level",
        intensity: "Intensity",
      },
      actions: {
        home: "← Home",
        homeShort: "Home",
        replay: "Play again",
        reset: "Reset scores",
      },
      hud: {
        score: "Score",
        combo: "Streak",
        accuracy: "Accuracy",
      },
      score: {
        best: "Best score: {score}",
        record: "Record {score}",
        new: "New",
      },
      difficulties: {
        calme: "Calm",
        rythme: "Rhythm",
        defi: "Challenge",
      },
      results: {
        eyebrow: "Session complete",
        success: "Mission complete",
        finished: "Session complete",
        summary: "{title}: {score} points, {accuracy} accuracy. {message}",
      },
      play: {
        defaultMode: "Mini-game",
        defaultTitle: "Game",
      },
      games: {
        meteors: {
          title: "Key Meteors",
          mode: "Reflexes",
          summary: "Keys fall from above: hit the right one and protect the line.",
          tag: "letters",
        },
        words: {
          title: "Word Workshop",
          mode: "Accuracy",
          summary: "Type lesson words and sentences without losing the thread.",
          tag: "words",
        },
        shortcuts: {
          title: "Shortcut Sprint",
          mode: "Method",
          summary: "Chain useful shortcuts to work faster.",
          tag: "Ctrl",
        },
        maze: {
          title: "Keyboard Maze",
          mode: "Movement",
          summary: "Explore, activate beacons, and reach the exit before time runs out.",
          tag: "arrows",
        },
        symbols: {
          title: "AltGr Forge",
          mode: "Symbols",
          summary: "Forge @, #, €, braces and other tricky keys with the right modifiers.",
          tag: "AltGr",
        },
        cipher: {
          title: "Secret Code",
          mode: "Memory",
          summary: "Watch a symbol sequence, then reproduce it without a mistake.",
          tag: "memory",
        },
        formula: {
          title: "Formula Fixer",
          mode: "Context",
          summary: "Repair emails, hashtags and formulas by typing the missing symbol.",
          tag: "@ # €",
        },
        rpg: {
          title: "Keyboard Adventure",
          mode: "RPG",
          summary: "Explore a top-down city, talk to NPCs, and complete 10 keyboard quests.",
          tag: "quest",
        },
      },
      meters: {
        time: "Time",
        progress: "Progress",
        beacons: "Beacons",
        charges: "Charges",
        sequences: "Sequences",
        repairs: "Repairs",
        quests: "Quests",
      },
      meteor: {
        line: "focus line",
        lives: "Lives",
        livesCount: "{count} lives",
        lost: "The line was hit too many times.",
        success: "The key storm is under control.",
        mission: "Press the displayed key before it crosses the line.",
      },
      word: {
        item: "Word {current} / {target}",
        timeUp: "Time is up.",
        success: "The word streak is validated.",
        enterHint: "Enter also validates a full sentence",
        mission: "Respect spaces, capitals, and punctuation.",
      },
      shortcut: {
        timeUp: "The round is over.",
        success: "You can chain shortcuts with confidence.",
        correct: "Correct",
        received: "Received: {combo}",
        yourTurn: "Your turn",
      },
      maze: {
        exitLabel: "E",
        timeUp: "The gate has closed.",
        exitSuccess: "Exit reached.",
        missingBeacons: "Some beacons still need activation.",
        beacon: "Beacon {label}",
        activate: "Activate the key, then head to the exit. Time: {seconds} s",
        remaining: "{count} beacons left",
        move: "Move with arrow keys or ZQSD. Time: {seconds} s",
      },
      symbols: {
        target: "Target symbol",
        combo: "Combination",
        queue: "forge queue",
        timeUp: "Forge time is over.",
        success: "The tricky symbols are forged.",
        mission: "Type the displayed symbol. Use the hint: AltGr, Shift, or direct key.",
      },
      cipher: {
        preview: "Watch",
        input: "Repeat",
        sequence: "Sequence {current} / {target}",
        timeUp: "The vault has locked.",
        success: "The secret code is memorized.",
        wrong: "Sequence scrambled, retry this one.",
        missionPreview: "Memorize the symbols in order.",
        missionInput: "Reproduce the sequence without looking at the model.",
      },
      formula: {
        placeholder: "missing symbol",
        timeUp: "The repair workshop is closing.",
        success: "The lines are repaired.",
        mission: "Type the symbol that replaces the square.",
      },
      rpg: {
        timeUp: "The bell rings before the adventure is complete.",
        success: "All keyboard quests are complete.",
        moveHint: "Move with arrow keys or ZQSD.",
        interactHint: "Press Enter near an NPC to start a quest.",
        completed: "Quest complete",
        alreadyDone: "This quest is already complete.",
        answer: "Answer",
        comboAnswer: "Expected shortcut",
        enterValidate: "Enter to validate. Escape to close.",
        questDone: "{count}/10 quests complete",
        nearby: "Talk to {name}",
        noQuest: "Explore the city and look for symbols.",
      },
    },
    es: {
      meta: {
        title: "Teclado Quest - 5.º / 4.º",
      },
      aria: {
        home: "Volver al inicio",
        language: "Idioma",
        sound: "Sonido",
        settings: "Ajustes de sesión",
        grade: "Nivel escolar",
        intensity: "Intensidad",
      },
      home: {
        eyebrow: "Entrenamiento de teclado",
        title: "Mini juegos cortos para ganar precisión.",
        description: "Elige un nivel, selecciona un reto y juega con el teclado. Las puntuaciones se guardan en este navegador.",
        choose: "Elige tu entrenamiento",
      },
      controls: {
        grade: "Nivel",
        intensity: "Intensidad",
      },
      actions: {
        home: "← Inicio",
        homeShort: "Inicio",
        replay: "Jugar otra vez",
        reset: "Reiniciar puntuaciones",
      },
      hud: {
        score: "Puntos",
        combo: "Racha",
        accuracy: "Precisión",
      },
      score: {
        best: "Mejor puntuación: {score}",
        record: "Récord {score}",
        new: "Nuevo",
      },
      difficulties: {
        calme: "Tranquilo",
        rythme: "Ritmo",
        defi: "Reto",
      },
      results: {
        eyebrow: "Sesión terminada",
        success: "Misión cumplida",
        finished: "Sesión terminada",
        summary: "{title}: {score} puntos, {accuracy} de precisión. {message}",
      },
      play: {
        defaultMode: "Mini juego",
        defaultTitle: "Juego",
      },
      games: {
        meteors: {
          title: "Meteoros de teclas",
          mode: "Reflejos",
          summary: "Caen teclas: pulsa la correcta y protege la línea.",
          tag: "letras",
        },
        words: {
          title: "Taller de palabras",
          mode: "Precisión",
          summary: "Escribe palabras y frases de clase sin perder el hilo.",
          tag: "palabras",
        },
        shortcuts: {
          title: "Atajos rápidos",
          mode: "Método",
          summary: "Encadena atajos útiles para trabajar más rápido.",
          tag: "Ctrl",
        },
        maze: {
          title: "Laberinto de teclado",
          mode: "Movimiento",
          summary: "Explora, activa balizas y llega a la salida antes del final.",
          tag: "flechas",
        },
        symbols: {
          title: "Forja AltGr",
          mode: "Símbolos",
          summary: "Forja @, #, €, llaves y otras teclas difíciles con los modificadores correctos.",
          tag: "AltGr",
        },
        cipher: {
          title: "Código secreto",
          mode: "Memoria",
          summary: "Observa una secuencia de símbolos y reprodúcela sin equivocarte.",
          tag: "memoria",
        },
        formula: {
          title: "Reparador de fórmulas",
          mode: "Contexto",
          summary: "Repara correos, hashtags y fórmulas escribiendo el símbolo que falta.",
          tag: "@ # €",
        },
        rpg: {
          title: "Aventura de teclado",
          mode: "RPG",
          summary: "Explora una ciudad top-down, habla con PNJ y completa 10 misiones de teclado.",
          tag: "misión",
        },
      },
      meters: {
        time: "Tiempo",
        progress: "Progreso",
        beacons: "Balizas",
        charges: "Cargas",
        sequences: "Secuencias",
        repairs: "Reparaciones",
        quests: "Misiones",
      },
      meteor: {
        line: "línea de concentración",
        lives: "Vidas",
        livesCount: "{count} vidas",
        lost: "La línea fue tocada demasiadas veces.",
        success: "La lluvia de teclas está dominada.",
        mission: "Pulsa la tecla mostrada antes de que cruce la línea.",
      },
      word: {
        item: "Palabra {current} / {target}",
        timeUp: "Se acabó el tiempo.",
        success: "La serie de palabras está validada.",
        enterHint: "Enter también valida una frase completa",
        mission: "Respeta espacios, acentos y puntuación.",
      },
      shortcut: {
        timeUp: "La ronda ha terminado.",
        success: "Encadenas los atajos con seguridad.",
        correct: "Correcto",
        received: "Recibido: {combo}",
        yourTurn: "Tu turno",
      },
      maze: {
        exitLabel: "S",
        timeUp: "La puerta se ha cerrado.",
        exitSuccess: "Salida alcanzada.",
        missingBeacons: "Quedan balizas por activar.",
        beacon: "Baliza {label}",
        activate: "Activa la tecla y ve a la salida. Tiempo: {seconds} s",
        remaining: "Quedan {count} balizas",
        move: "Muévete con flechas o ZQSD. Tiempo: {seconds} s",
      },
      symbols: {
        target: "Símbolo objetivo",
        combo: "Combinación",
        queue: "cola de forja",
        timeUp: "Se acabó el tiempo de forja.",
        success: "Los símbolos difíciles están forjados.",
        mission: "Escribe el símbolo mostrado. Usa la pista: AltGr, Mayús o tecla directa.",
      },
      cipher: {
        preview: "Observa",
        input: "Repite",
        sequence: "Secuencia {current} / {target}",
        timeUp: "La caja fuerte se ha bloqueado.",
        success: "El código secreto está memorizado.",
        wrong: "Secuencia mezclada, repite esta.",
        missionPreview: "Memoriza los símbolos en orden.",
        missionInput: "Reproduce la secuencia sin mirar el modelo.",
      },
      formula: {
        placeholder: "símbolo que falta",
        timeUp: "El taller de reparación cierra.",
        success: "Las líneas están reparadas.",
        mission: "Escribe el símbolo que sustituye al cuadrado.",
      },
      rpg: {
        timeUp: "Suena la campana antes de terminar la aventura.",
        success: "Todas las misiones de teclado están completas.",
        moveHint: "Muévete con flechas o ZQSD.",
        interactHint: "Pulsa Enter cerca de un PNJ para iniciar una misión.",
        completed: "Misión completada",
        alreadyDone: "Esta misión ya está validada.",
        answer: "Respuesta",
        comboAnswer: "Atajo esperado",
        enterValidate: "Enter para validar. Escape para cerrar.",
        questDone: "{count}/10 misiones completadas",
        nearby: "Habla con {name}",
        noQuest: "Explora la ciudad y busca símbolos.",
      },
    },
  };

  CQ.localizedGradeData = {
    fr: {
      "5e": {
        keys: ["a", "z", "e", "r", "t", "y", "u", "i", "o", "p", "q", "s", "d", "f", "g", "h", "j", "k", "l", "m"],
        extraKeys: ["é", "è", "à", "ç", ",", ".", ";", "?", "1", "2", "3", "4", "5"],
        words: [
          "fraction",
          "croquis",
          "citadelle",
          "volcan",
          "bibliothèque",
          "moyen âge",
          "énergie",
          "proportion",
          "Le chevalier ajuste son heaume.",
          "Une carte claire aide la mémoire.",
          "La rivière traverse la vallée.",
          "Le résultat se vérifie en calculant.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copier" },
          { combo: "Ctrl+V", action: "coller" },
          { combo: "Ctrl+Z", action: "annuler" },
          { combo: "Ctrl+A", action: "tout sélectionner" },
          { combo: "Ctrl+S", action: "enregistrer" },
          { combo: "Ctrl+F", action: "chercher" },
          { combo: "Tab", action: "champ suivant" },
          { combo: "Shift+Tab", action: "champ précédent" },
          { combo: "Enter", action: "valider" },
          { combo: "Escape", action: "fermer" },
        ],
        formulas: [
          { text: "contact□college.fr", symbol: "@" },
          { text: "□maths", symbol: "#" },
          { text: "prix : 12□", symbol: "€" },
          { text: "note□10", symbol: "/" },
          { text: "groupe□5e", symbol: "_" },
          { text: "fin de phrase□", symbol: "." },
        ],
      },
      "4e": {
        keys: ["a", "z", "e", "r", "t", "y", "u", "i", "o", "p", "q", "s", "d", "f", "g", "h", "j", "k", "l", "m", "w", "x", "c", "v", "b", "n"],
        extraKeys: ["é", "è", "à", "ç", ",", ".", ";", ":", "!", "?", "(", ")", "6", "7", "8", "9"],
        words: [
          "équation",
          "révolution",
          "hypothèse",
          "chlorophylle",
          "citoyenneté",
          "algorithmique",
          "proportionnalité",
          "coordonnées",
          "La vitesse dépend de la distance et du temps.",
          "Un argument solide s'appuie sur des preuves.",
          "L'expérience confirme l'hypothèse.",
          "Le graphique compare deux grandeurs.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copier" },
          { combo: "Ctrl+V", action: "coller" },
          { combo: "Ctrl+X", action: "couper" },
          { combo: "Ctrl+Z", action: "annuler" },
          { combo: "Ctrl+Y", action: "rétablir" },
          { combo: "Ctrl+S", action: "enregistrer" },
          { combo: "Ctrl+F", action: "chercher" },
          { combo: "Ctrl+B", action: "gras" },
          { combo: "Ctrl+I", action: "italique" },
          { combo: "Ctrl+U", action: "souligner" },
          { combo: "Shift+Tab", action: "champ précédent" },
          { combo: "Escape", action: "fermer" },
        ],
        formulas: [
          { text: "eleve□college.fr", symbol: "@" },
          { text: "□algorithmique", symbol: "#" },
          { text: "budget = 18□", symbol: "€" },
          { text: "tableau□3]", symbol: "[" },
          { text: "tableau[3□", symbol: "]" },
          { text: "objet □ cle: 4 }", symbol: "{" },
          { text: "objet { cle: 4 □", symbol: "}" },
          { text: "a □ b", symbol: "|" },
        ],
      },
    },
    en: {
      "5e": {
        keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "e", "r", "t", "u", "i", "o", "p", "c", "v", "b", "n"],
        extraKeys: [",", ".", ";", "?", "!", "'", "1", "2", "3", "4", "5"],
        words: [
          "fraction",
          "sketch",
          "castle",
          "volcano",
          "library",
          "middle age",
          "energy",
          "proportion",
          "The knight adjusts his helmet.",
          "A clear map helps memory.",
          "The river crosses the valley.",
          "The result is checked by calculating.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copy" },
          { combo: "Ctrl+V", action: "paste" },
          { combo: "Ctrl+Z", action: "undo" },
          { combo: "Ctrl+A", action: "select all" },
          { combo: "Ctrl+S", action: "save" },
          { combo: "Ctrl+F", action: "find" },
          { combo: "Tab", action: "next field" },
          { combo: "Shift+Tab", action: "previous field" },
          { combo: "Enter", action: "confirm" },
          { combo: "Escape", action: "close" },
        ],
        formulas: [
          { text: "contact□school.org", symbol: "@" },
          { text: "□science", symbol: "#" },
          { text: "price: 12□", symbol: "€" },
          { text: "score□10", symbol: "/" },
          { text: "group□grade7", symbol: "_" },
          { text: "end of line□", symbol: "." },
        ],
      },
      "4e": {
        keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m"],
        extraKeys: [",", ".", ";", ":", "!", "?", "(", ")", "'", "6", "7", "8", "9"],
        words: [
          "equation",
          "revolution",
          "hypothesis",
          "chlorophyll",
          "citizenship",
          "algorithm",
          "proportionality",
          "coordinates",
          "Speed depends on distance and time.",
          "A strong argument relies on evidence.",
          "The experiment confirms the hypothesis.",
          "The graph compares two quantities.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copy" },
          { combo: "Ctrl+V", action: "paste" },
          { combo: "Ctrl+X", action: "cut" },
          { combo: "Ctrl+Z", action: "undo" },
          { combo: "Ctrl+Y", action: "redo" },
          { combo: "Ctrl+S", action: "save" },
          { combo: "Ctrl+F", action: "find" },
          { combo: "Ctrl+B", action: "bold" },
          { combo: "Ctrl+I", action: "italic" },
          { combo: "Ctrl+U", action: "underline" },
          { combo: "Shift+Tab", action: "previous field" },
          { combo: "Escape", action: "close" },
        ],
        formulas: [
          { text: "student□school.org", symbol: "@" },
          { text: "□algorithm", symbol: "#" },
          { text: "budget = 18□", symbol: "€" },
          { text: "array□3]", symbol: "[" },
          { text: "array[3□", symbol: "]" },
          { text: "object □ key: 4 }", symbol: "{" },
          { text: "object { key: 4 □", symbol: "}" },
          { text: "a □ b", symbol: "|" },
        ],
      },
    },
    es: {
      "5e": {
        keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "e", "r", "t", "u", "i", "o", "p", "c", "v", "b", "n"],
        extraKeys: ["á", "é", "í", "ó", "ú", "ñ", ",", ".", ";", "?", "1", "2", "3", "4", "5"],
        words: [
          "fracción",
          "croquis",
          "ciudadela",
          "volcán",
          "biblioteca",
          "edad media",
          "energía",
          "proporción",
          "El caballero ajusta su casco.",
          "Un mapa claro ayuda a la memoria.",
          "El río cruza el valle.",
          "El resultado se comprueba calculando.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copiar" },
          { combo: "Ctrl+V", action: "pegar" },
          { combo: "Ctrl+Z", action: "deshacer" },
          { combo: "Ctrl+A", action: "seleccionar todo" },
          { combo: "Ctrl+S", action: "guardar" },
          { combo: "Ctrl+F", action: "buscar" },
          { combo: "Tab", action: "campo siguiente" },
          { combo: "Shift+Tab", action: "campo anterior" },
          { combo: "Enter", action: "validar" },
          { combo: "Escape", action: "cerrar" },
        ],
        formulas: [
          { text: "contacto□colegio.es", symbol: "@" },
          { text: "□ciencias", symbol: "#" },
          { text: "precio: 12□", symbol: "€" },
          { text: "nota□10", symbol: "/" },
          { text: "grupo□5e", symbol: "_" },
          { text: "fin de línea□", symbol: "." },
        ],
      },
      "4e": {
        keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m"],
        extraKeys: ["á", "é", "í", "ó", "ú", "ñ", ",", ".", ";", ":", "!", "?", "(", ")", "6", "7", "8", "9"],
        words: [
          "ecuación",
          "revolución",
          "hipótesis",
          "clorofila",
          "ciudadanía",
          "algoritmo",
          "proporcionalidad",
          "coordenadas",
          "La velocidad depende de la distancia y del tiempo.",
          "Un argumento sólido se apoya en pruebas.",
          "El experimento confirma la hipótesis.",
          "El gráfico compara dos magnitudes.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copiar" },
          { combo: "Ctrl+V", action: "pegar" },
          { combo: "Ctrl+X", action: "cortar" },
          { combo: "Ctrl+Z", action: "deshacer" },
          { combo: "Ctrl+Y", action: "rehacer" },
          { combo: "Ctrl+S", action: "guardar" },
          { combo: "Ctrl+F", action: "buscar" },
          { combo: "Ctrl+B", action: "negrita" },
          { combo: "Ctrl+I", action: "cursiva" },
          { combo: "Ctrl+U", action: "subrayar" },
          { combo: "Shift+Tab", action: "campo anterior" },
          { combo: "Escape", action: "cerrar" },
        ],
        formulas: [
          { text: "alumno□colegio.es", symbol: "@" },
          { text: "□algoritmo", symbol: "#" },
          { text: "presupuesto = 18□", symbol: "€" },
          { text: "tabla□3]", symbol: "[" },
          { text: "tabla[3□", symbol: "]" },
          { text: "objeto □ clave: 4 }", symbol: "{" },
          { text: "objeto { clave: 4 □", symbol: "}" },
          { text: "a □ b", symbol: "|" },
        ],
      },
    },
  };
})(window.CQ = window.CQ || {});
