(function registerData(CQ) {
  CQ.STORAGE_KEY = "clavierQuestScores:v1";
  CQ.LANGUAGE_STORAGE_KEY = "clavierQuestLanguage:v1";
  CQ.DEFAULT_LANGUAGE = "fr";

  CQ.languages = [
    { id: "fr", label: "FR", name: "Français" },
    { id: "en", label: "EN", name: "English" },
    { id: "es", label: "ES", name: "Español" },
  ];

  CQ.difficultySettings = {
    calme: {
      speed: 0.82,
      spawn: 1.15,
      time: 75,
      lives: 6,
      tokens: 6,
    },
    rythme: {
      speed: 1,
      spawn: 0.9,
      time: 65,
      lives: 5,
      tokens: 8,
    },
    defi: {
      speed: 1.22,
      spawn: 0.7,
      time: 55,
      lives: 4,
      tokens: 10,
    },
  };

  CQ.gradeTuning = {
    "5e": {
      speedMultiplier: 1,
      spawnMultiplier: 1,
      timeMultiplier: 1,
      livesDelta: 0,
      tokensDelta: 0,
      wordTargetBonus: 0,
      shortcutGoalBonus: 0,
      meteorExtraPool: 0,
    },
    "4e": {
      speedMultiplier: 1.18,
      spawnMultiplier: 0.82,
      timeMultiplier: 0.9,
      livesDelta: -1,
      tokensDelta: 2,
      wordTargetBonus: 2,
      shortcutGoalBonus: 3,
      meteorExtraPool: 4,
    },
  };

  CQ.gameCards = [
    {
      id: "meteors",
      art: ["A", "Z", "E", "R", "T", "Y", "U", "I", "O", "P", "Q", "S"],
    },
    {
      id: "words",
      art: ["é", "q", "u", "a", "t", "i", "o", "n", ".", ";", "?", "!"],
    },
    {
      id: "shortcuts",
      art: ["Ctrl", "C", "V", "Z", "S", "F", "Tab", "↵", "Esc", "B", "I", "U"],
    },
    {
      id: "maze",
      art: ["↑", "←", "↓", "→", "Z", "Q", "S", "D", "A", "E", "R", "T"],
    },
  ];

  CQ.translations = {
    fr: {
      meta: {
        title: "Clavier Quest - 5e / 4e",
      },
      aria: {
        home: "Retour accueil",
        language: "Langue",
        sound: "Son",
        settings: "Réglages de session",
        grade: "Niveau scolaire",
        intensity: "Intensité",
      },
      home: {
        eyebrow: "Entraînement clavier",
        title: "Des mini-jeux courts pour gagner en précision.",
        description: "Sélectionne un niveau, choisis un défi, puis joue au clavier. Les scores restent enregistrés dans ce navigateur.",
        choose: "Choisis ton entraînement",
      },
      controls: {
        grade: "Niveau",
        intensity: "Intensité",
      },
      actions: {
        home: "← Accueil",
        homeShort: "Accueil",
        replay: "Rejouer",
        reset: "Remettre les scores à zéro",
      },
      hud: {
        score: "Score",
        combo: "Série",
        accuracy: "Précision",
      },
      score: {
        best: "Meilleur score : {score}",
        record: "Record {score}",
        new: "Nouveau",
      },
      difficulties: {
        calme: "Calme",
        rythme: "Rythme",
        defi: "Défi",
      },
      results: {
        eyebrow: "Session terminée",
        success: "Mission réussie",
        finished: "Session terminée",
        summary: "{title} : {score} points, {accuracy} de précision. {message}",
      },
      play: {
        defaultMode: "Mini-jeu",
        defaultTitle: "Jeu",
      },
      games: {
        meteors: {
          title: "Météores de touches",
          mode: "Réflexes",
          summary: "Des touches tombent : vise juste, garde la série et protège la ligne.",
          tag: "lettres",
        },
        words: {
          title: "Atelier des mots",
          mode: "Précision",
          summary: "Écris des mots et phrases de cours sans perdre le fil.",
          tag: "mots",
        },
        shortcuts: {
          title: "Raccourcis express",
          mode: "Méthode",
          summary: "Enchaîne les raccourcis utiles pour travailler plus vite.",
          tag: "Ctrl",
        },
        maze: {
          title: "Labyrinthe clavier",
          mode: "Déplacement",
          summary: "Explore, ouvre les bornes et rejoins la sortie avant la fin.",
          tag: "flèches",
        },
      },
      meters: {
        time: "Temps",
        progress: "Progression",
        beacons: "Bornes",
      },
      meteor: {
        line: "ligne de concentration",
        lives: "Vies",
        livesCount: "{count} vies",
        lost: "La ligne a été touchée trop souvent.",
        success: "La pluie de touches est maîtrisée.",
        mission: "Appuie sur la touche affichée avant qu'elle traverse la ligne.",
      },
      word: {
        item: "Mot {current} / {target}",
        timeUp: "Le temps est écoulé.",
        success: "La série de mots est validée.",
        enterHint: "Entrée valide aussi une phrase complète",
        mission: "Respecte les accents, les espaces et la ponctuation.",
      },
      shortcut: {
        timeUp: "La manche est terminée.",
        success: "Les raccourcis s'enchaînent avec assurance.",
        correct: "Correct",
        received: "Reçu : {combo}",
        yourTurn: "À toi",
      },
      maze: {
        exitLabel: "S",
        timeUp: "La porte s'est refermée.",
        exitSuccess: "Sortie atteinte.",
        missingBeacons: "Il reste des bornes à activer.",
        beacon: "Borne {label}",
        activate: "Active la touche puis file vers la sortie. Temps : {seconds} s",
        remaining: "{count} bornes restantes",
        move: "Déplacement avec flèches ou ZQSD. Temps : {seconds} s",
      },
    },
    en: {
      meta: {
        title: "Keyboard Quest - Grade 7 / 8",
      },
      aria: {
        home: "Back home",
        language: "Language",
        sound: "Sound",
        settings: "Session settings",
        grade: "School level",
        intensity: "Intensity",
      },
      home: {
        eyebrow: "Keyboard training",
        title: "Short mini-games to build speed and accuracy.",
        description: "Choose a level, pick a challenge, then play with the keyboard. Scores are saved in this browser.",
        choose: "Choose your training",
      },
      controls: {
        grade: "Level",
        intensity: "Intensity",
      },
      actions: {
        home: "← Home",
        homeShort: "Home",
        replay: "Play again",
        reset: "Reset scores",
      },
      hud: {
        score: "Score",
        combo: "Streak",
        accuracy: "Accuracy",
      },
      score: {
        best: "Best score: {score}",
        record: "Record {score}",
        new: "New",
      },
      difficulties: {
        calme: "Calm",
        rythme: "Rhythm",
        defi: "Challenge",
      },
      results: {
        eyebrow: "Session complete",
        success: "Mission complete",
        finished: "Session complete",
        summary: "{title}: {score} points, {accuracy} accuracy. {message}",
      },
      play: {
        defaultMode: "Mini-game",
        defaultTitle: "Game",
      },
      games: {
        meteors: {
          title: "Key Meteors",
          mode: "Reflexes",
          summary: "Keys fall from above: hit the right one and protect the line.",
          tag: "letters",
        },
        words: {
          title: "Word Workshop",
          mode: "Accuracy",
          summary: "Type lesson words and sentences without losing the thread.",
          tag: "words",
        },
        shortcuts: {
          title: "Shortcut Sprint",
          mode: "Method",
          summary: "Chain useful shortcuts to work faster.",
          tag: "Ctrl",
        },
        maze: {
          title: "Keyboard Maze",
          mode: "Movement",
          summary: "Explore, activate beacons, and reach the exit before time runs out.",
          tag: "arrows",
        },
      },
      meters: {
        time: "Time",
        progress: "Progress",
        beacons: "Beacons",
      },
      meteor: {
        line: "focus line",
        lives: "Lives",
        livesCount: "{count} lives",
        lost: "The line was hit too many times.",
        success: "The key storm is under control.",
        mission: "Press the displayed key before it crosses the line.",
      },
      word: {
        item: "Word {current} / {target}",
        timeUp: "Time is up.",
        success: "The word streak is validated.",
        enterHint: "Enter also validates a full sentence",
        mission: "Respect spaces, capitals, and punctuation.",
      },
      shortcut: {
        timeUp: "The round is over.",
        success: "You can chain shortcuts with confidence.",
        correct: "Correct",
        received: "Received: {combo}",
        yourTurn: "Your turn",
      },
      maze: {
        exitLabel: "E",
        timeUp: "The gate has closed.",
        exitSuccess: "Exit reached.",
        missingBeacons: "Some beacons still need activation.",
        beacon: "Beacon {label}",
        activate: "Activate the key, then head to the exit. Time: {seconds} s",
        remaining: "{count} beacons left",
        move: "Move with arrow keys or ZQSD. Time: {seconds} s",
      },
    },
    es: {
      meta: {
        title: "Teclado Quest - 5.º / 4.º",
      },
      aria: {
        home: "Volver al inicio",
        language: "Idioma",
        sound: "Sonido",
        settings: "Ajustes de sesión",
        grade: "Nivel escolar",
        intensity: "Intensidad",
      },
      home: {
        eyebrow: "Entrenamiento de teclado",
        title: "Mini juegos cortos para ganar precisión.",
        description: "Elige un nivel, selecciona un reto y juega con el teclado. Las puntuaciones se guardan en este navegador.",
        choose: "Elige tu entrenamiento",
      },
      controls: {
        grade: "Nivel",
        intensity: "Intensidad",
      },
      actions: {
        home: "← Inicio",
        homeShort: "Inicio",
        replay: "Jugar otra vez",
        reset: "Reiniciar puntuaciones",
      },
      hud: {
        score: "Puntos",
        combo: "Racha",
        accuracy: "Precisión",
      },
      score: {
        best: "Mejor puntuación: {score}",
        record: "Récord {score}",
        new: "Nuevo",
      },
      difficulties: {
        calme: "Tranquilo",
        rythme: "Ritmo",
        defi: "Reto",
      },
      results: {
        eyebrow: "Sesión terminada",
        success: "Misión cumplida",
        finished: "Sesión terminada",
        summary: "{title}: {score} puntos, {accuracy} de precisión. {message}",
      },
      play: {
        defaultMode: "Mini juego",
        defaultTitle: "Juego",
      },
      games: {
        meteors: {
          title: "Meteoros de teclas",
          mode: "Reflejos",
          summary: "Caen teclas: pulsa la correcta y protege la línea.",
          tag: "letras",
        },
        words: {
          title: "Taller de palabras",
          mode: "Precisión",
          summary: "Escribe palabras y frases de clase sin perder el hilo.",
          tag: "palabras",
        },
        shortcuts: {
          title: "Atajos rápidos",
          mode: "Método",
          summary: "Encadena atajos útiles para trabajar más rápido.",
          tag: "Ctrl",
        },
        maze: {
          title: "Laberinto de teclado",
          mode: "Movimiento",
          summary: "Explora, activa balizas y llega a la salida antes del final.",
          tag: "flechas",
        },
      },
      meters: {
        time: "Tiempo",
        progress: "Progreso",
        beacons: "Balizas",
      },
      meteor: {
        line: "línea de concentración",
        lives: "Vidas",
        livesCount: "{count} vidas",
        lost: "La línea fue tocada demasiadas veces.",
        success: "La lluvia de teclas está dominada.",
        mission: "Pulsa la tecla mostrada antes de que cruce la línea.",
      },
      word: {
        item: "Palabra {current} / {target}",
        timeUp: "Se acabó el tiempo.",
        success: "La serie de palabras está validada.",
        enterHint: "Enter también valida una frase completa",
        mission: "Respeta espacios, acentos y puntuación.",
      },
      shortcut: {
        timeUp: "La ronda ha terminado.",
        success: "Encadenas los atajos con seguridad.",
        correct: "Correcto",
        received: "Recibido: {combo}",
        yourTurn: "Tu turno",
      },
      maze: {
        exitLabel: "S",
        timeUp: "La puerta se ha cerrado.",
        exitSuccess: "Salida alcanzada.",
        missingBeacons: "Quedan balizas por activar.",
        beacon: "Baliza {label}",
        activate: "Activa la tecla y ve a la salida. Tiempo: {seconds} s",
        remaining: "Quedan {count} balizas",
        move: "Muévete con flechas o ZQSD. Tiempo: {seconds} s",
      },
    },
  };

  CQ.localizedGradeData = {
    fr: {
      "5e": {
        keys: ["a", "z", "e", "r", "t", "y", "u", "i", "o", "p", "q", "s", "d", "f", "g", "h", "j", "k", "l", "m"],
        extraKeys: ["é", "è", "à", "ç", ",", ".", ";", "?", "1", "2", "3", "4", "5"],
        words: [
          "fraction",
          "croquis",
          "citadelle",
          "volcan",
          "bibliothèque",
          "moyen âge",
          "énergie",
          "proportion",
          "Le chevalier ajuste son heaume.",
          "Une carte claire aide la mémoire.",
          "La rivière traverse la vallée.",
          "Le résultat se vérifie en calculant.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copier" },
          { combo: "Ctrl+V", action: "coller" },
          { combo: "Ctrl+Z", action: "annuler" },
          { combo: "Ctrl+A", action: "tout sélectionner" },
          { combo: "Ctrl+S", action: "enregistrer" },
          { combo: "Ctrl+F", action: "chercher" },
          { combo: "Tab", action: "champ suivant" },
          { combo: "Shift+Tab", action: "champ précédent" },
          { combo: "Enter", action: "valider" },
          { combo: "Escape", action: "fermer" },
        ],
      },
      "4e": {
        keys: ["a", "z", "e", "r", "t", "y", "u", "i", "o", "p", "q", "s", "d", "f", "g", "h", "j", "k", "l", "m", "w", "x", "c", "v", "b", "n"],
        extraKeys: ["é", "è", "à", "ç", ",", ".", ";", ":", "!", "?", "(", ")", "6", "7", "8", "9"],
        words: [
          "équation",
          "révolution",
          "hypothèse",
          "chlorophylle",
          "citoyenneté",
          "algorithmique",
          "proportionnalité",
          "coordonnées",
          "La vitesse dépend de la distance et du temps.",
          "Un argument solide s'appuie sur des preuves.",
          "L'expérience confirme l'hypothèse.",
          "Le graphique compare deux grandeurs.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copier" },
          { combo: "Ctrl+V", action: "coller" },
          { combo: "Ctrl+X", action: "couper" },
          { combo: "Ctrl+Z", action: "annuler" },
          { combo: "Ctrl+Y", action: "rétablir" },
          { combo: "Ctrl+S", action: "enregistrer" },
          { combo: "Ctrl+F", action: "chercher" },
          { combo: "Ctrl+B", action: "gras" },
          { combo: "Ctrl+I", action: "italique" },
          { combo: "Ctrl+U", action: "souligner" },
          { combo: "Shift+Tab", action: "champ précédent" },
          { combo: "Escape", action: "fermer" },
        ],
      },
    },
    en: {
      "5e": {
        keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "e", "r", "t", "u", "i", "o", "p", "c", "v", "b", "n"],
        extraKeys: [",", ".", ";", "?", "!", "'", "1", "2", "3", "4", "5"],
        words: [
          "fraction",
          "sketch",
          "castle",
          "volcano",
          "library",
          "middle age",
          "energy",
          "proportion",
          "The knight adjusts his helmet.",
          "A clear map helps memory.",
          "The river crosses the valley.",
          "The result is checked by calculating.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copy" },
          { combo: "Ctrl+V", action: "paste" },
          { combo: "Ctrl+Z", action: "undo" },
          { combo: "Ctrl+A", action: "select all" },
          { combo: "Ctrl+S", action: "save" },
          { combo: "Ctrl+F", action: "find" },
          { combo: "Tab", action: "next field" },
          { combo: "Shift+Tab", action: "previous field" },
          { combo: "Enter", action: "confirm" },
          { combo: "Escape", action: "close" },
        ],
      },
      "4e": {
        keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m"],
        extraKeys: [",", ".", ";", ":", "!", "?", "(", ")", "'", "6", "7", "8", "9"],
        words: [
          "equation",
          "revolution",
          "hypothesis",
          "chlorophyll",
          "citizenship",
          "algorithm",
          "proportionality",
          "coordinates",
          "Speed depends on distance and time.",
          "A strong argument relies on evidence.",
          "The experiment confirms the hypothesis.",
          "The graph compares two quantities.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copy" },
          { combo: "Ctrl+V", action: "paste" },
          { combo: "Ctrl+X", action: "cut" },
          { combo: "Ctrl+Z", action: "undo" },
          { combo: "Ctrl+Y", action: "redo" },
          { combo: "Ctrl+S", action: "save" },
          { combo: "Ctrl+F", action: "find" },
          { combo: "Ctrl+B", action: "bold" },
          { combo: "Ctrl+I", action: "italic" },
          { combo: "Ctrl+U", action: "underline" },
          { combo: "Shift+Tab", action: "previous field" },
          { combo: "Escape", action: "close" },
        ],
      },
    },
    es: {
      "5e": {
        keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "e", "r", "t", "u", "i", "o", "p", "c", "v", "b", "n"],
        extraKeys: ["á", "é", "í", "ó", "ú", "ñ", ",", ".", ";", "?", "1", "2", "3", "4", "5"],
        words: [
          "fracción",
          "croquis",
          "ciudadela",
          "volcán",
          "biblioteca",
          "edad media",
          "energía",
          "proporción",
          "El caballero ajusta su casco.",
          "Un mapa claro ayuda a la memoria.",
          "El río cruza el valle.",
          "El resultado se comprueba calculando.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copiar" },
          { combo: "Ctrl+V", action: "pegar" },
          { combo: "Ctrl+Z", action: "deshacer" },
          { combo: "Ctrl+A", action: "seleccionar todo" },
          { combo: "Ctrl+S", action: "guardar" },
          { combo: "Ctrl+F", action: "buscar" },
          { combo: "Tab", action: "campo siguiente" },
          { combo: "Shift+Tab", action: "campo anterior" },
          { combo: "Enter", action: "validar" },
          { combo: "Escape", action: "cerrar" },
        ],
      },
      "4e": {
        keys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m"],
        extraKeys: ["á", "é", "í", "ó", "ú", "ñ", ",", ".", ";", ":", "!", "?", "(", ")", "6", "7", "8", "9"],
        words: [
          "ecuación",
          "revolución",
          "hipótesis",
          "clorofila",
          "ciudadanía",
          "algoritmo",
          "proporcionalidad",
          "coordenadas",
          "La velocidad depende de la distancia y del tiempo.",
          "Un argumento sólido se apoya en pruebas.",
          "El experimento confirma la hipótesis.",
          "El gráfico compara dos magnitudes.",
        ],
        shortcuts: [
          { combo: "Ctrl+C", action: "copiar" },
          { combo: "Ctrl+V", action: "pegar" },
          { combo: "Ctrl+X", action: "cortar" },
          { combo: "Ctrl+Z", action: "deshacer" },
          { combo: "Ctrl+Y", action: "rehacer" },
          { combo: "Ctrl+S", action: "guardar" },
          { combo: "Ctrl+F", action: "buscar" },
          { combo: "Ctrl+B", action: "negrita" },
          { combo: "Ctrl+I", action: "cursiva" },
          { combo: "Ctrl+U", action: "subrayar" },
          { combo: "Shift+Tab", action: "campo anterior" },
          { combo: "Escape", action: "cerrar" },
        ],
      },
    },
  };
})(window.CQ = window.CQ || {});
